"""add_media_type_exercise_images

Revision ID: fea423061f80
Revises: 9b6f3e2fd6cd
Create Date: 2026-07-16 23:08:08.444122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fea423061f80'
down_revision: Union[str, None] = '9b6f3e2fd6cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_images', sa.Column('media_type', sa.Enum('image', 'video', name='media_type'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise_images', 'media_type')
    # ### end Alembic commands ###
